set_game_task:
  description: >
    Set the initial state of the game. This includes making the cards repartition
    between the players where each player gets 2 cards. After that, the game master
    will ask the player_1 to bet. The way the state changed is by means of updating
    a json file that contains the state of the game.
  expected_output: >
    The instruction to the player_1 to bet.
  agent: game_master
# TODO: Add the tools that will be used for setting the initial the game state.

player_1_bet_task:
  description: >
    The player_1 sees his cards on hand, analyzes the community cards
    in relationship the cards on hand and makes a bet accordingly.
  expected_output: >
    Show your bet (not your cards) and tell player_2 to place a bet.
  agent: player_1
